apiVersion: v2
name: vllm
description: A Helm chart for deploying vLLM inference server
type: application
version: 0.1.0
appVersion: "0.6.0"
keywords:
  - vllm
  - llm
  - inference
  - ai
maintainers:
  - name: hyperbolic-labs
