# Please make sure that the Grafana Cloud credentials are in the Kubernetes cluster as a secret
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/learnwithtwoheads/argocd-bootstrapping.git
    targetRevision: main
    path: app-of-apps
    helm:
      valuesObject:
        global:
          # Default source repository URL
          repoURL: https://github.com/learnwithtwoheads/argocd-bootstrapping.git
          # Target revision (branch, tag, or commit)
          targetRevision: main
          # Default destination cluster
          destination:
            server: https://kubernetes.default.svc
            # Default namespace (can be overridden per application)
            namespace: default

        # ArgoCD project to deploy applications to
        project: default

        # List of applications to deploy
        applications:
          - name: datadog
            targetRevision: 3.149.3
            repoURL: https://helm.datadoghq.com
            namespace: datadog
            helm:
              chart: datadog
              releaseName: datadog
              valuesObject:
                datadog:
                  kubernetesResourcesAnnotationsAsTags:
                    pods:
                      hyperbolic.xyz/tenant: tenant
                  env:
                    - name: DD_COLLECT_GPU_TAGS
                      value: "true"
                    - name: DD_HOSTNAME
                      valueFrom:
                        fieldRef:
                          fieldPath: spec.nodeName
                  site: "us5.datadoghq.com"
                  kubelet:
                    tlsVerify: false
                  clusterName: inference-cluster
                  apiKeyExistingSecret: datadog-secret
                  gpuMonitoring:
                    enabled: true
                    privilegedMode: true
                  prometheusScrape:
                    enabled: true
                    serviceEndpoints: true
                    additionalConfigs:
                      - configurations:
                          - send_histograms_buckets: true
                            histogram_buckets_as_distributions: true
                            timeout: 5
          - name: otel-collector-metrics
            targetRevision: 0.140.0
            repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
            helm:
              chart: opentelemetry-collector
              releaseName: otel-collector-metrics
              valuesObject:
                mode: deployment
                extraEnvsFrom:
                  - secretRef:
                      name: grafana-cloud-credentials

                image:
                  tag: "0.132.2"
                  repository: otel/opentelemetry-collector-contrib

                replicaCount: 1

                # These are required for the prometheus scraping to work on the Kubernetes services.
                clusterRole:
                  create: true
                  name: "otel-collector-clusterrole"
                  rules:
                    - apiGroups: [""]
                      resources: ["services"]
                      verbs: ["get", "list", "watch"]
                  clusterRoleBinding:
                    name: "otel-collector-clusterrolebinding"

                serviceAccount:
                  create: true
                  name: "otel-collector-serviceaccount"

                config:
                  receivers:
                    prometheus:
                      config:
                        scrape_configs:
                          - job_name: 'kubernetes-services'
                            scrape_interval: 10s
                            kubernetes_sd_configs:
                              - role: service
                                namespaces:
                                  own_namespace: false
                                  names:
                                    - default
                                    - traefik

                    otlp:
                      protocols:
                        grpc:
                          endpoint: 0.0.0.0:4317
                        http:
                          endpoint: 0.0.0.0:4318

                  processors:
                    batch:
                      send_batch_size: 8192
                      timeout: 5s

                  exporters:
                    prometheusremotewrite:
                      endpoint: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
                      auth:
                        authenticator: basicauth

                  service:
                    extensions: [health_check, basicauth]
                    pipelines:
                      metrics:
                        receivers: [prometheus]
                        processors: [batch]
                        exporters: [prometheusremotewrite]

                  extensions:
                    basicauth:
                      client_auth:
                        username: ${env:GRAFANA_CLOUD_USERNAME}
                        password: ${env:GRAFANA_CLOUD_PASSWORD}

          - name: cert-manager
            targetRevision: v1.19.1
            repoURL: https://charts.jetstack.io
            namespace: cert-manager
            helm:
              chart: cert-manager
              releaseName: cert-manager
              valuesObject:
                crds:
                  enabled: true
          - name: traefik
            targetRevision: 37.4.0
            repoURL: https://traefik.github.io/charts
            namespace: traefik
            helm:
              chart: traefik
              releaseName: traefik
              valuesObject:
                deployment:
                  replicas: 5
                metrics:
                  prometheus:
                    entryPoint: metrics
                    service:
                      enabled: true

        # Default sync policy for all applications (can be overridden per app)
        defaultSyncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
            - PruneLast=true

        # Default retry policy
        defaultRetryPolicy:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
          destination:
            server: https://kubernetes.default.svc
            namespace: argocd
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true
